### Request

POST localhost:8080/products
Content-Type: application/json

{
  "name": "테스트",
  "price": "5000",
  "image-url": "testimage"
}

### Response

HTTP/1.1 201
Location: /products/8
Content-Type: application/json
Transfer-Encoding: chunked
Date: Thu, 04 May 2023 02:47:25 GMT
Keep-Alive: timeout=60
Connection: keep-alive
