DROP TABLE IF EXISTS product;

CREATE TABLE product(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    PRIMARY KEY (id)
);
