insert into customer (username, email)
values ('puterism', 'email1@email.com'),
       ('tanney-102', 'email2@email.com'),
       ('jho2301', 'email3@email.com'),
       ('365kim', 'email4@email.com'),
       ('dudtjr913', 'email5@email.com'),
       ('jum0', 'email6@email.com'),
       ('hyuuunjukim', 'email7@email.com'),
       ('zereight', 'email8@email.com'),
       ('devhyun637', 'email9@email.com'),
       ('swon3210', 'email10@email.com'),
       ('bigsaigon333', 'email11@email.com'),
       ('yungo1846', 'email12@email.com'),
       ('zigsong', 'email13@email.com'),
       ('iborymagic', 'email14@email.com'),
       ('0307kwon', 'email15@email.com'),
       ('gwangyeol-im', 'email16@email.com'),
       ('shinsehantan', 'email17@email.com'),
       ('ddongule', 'email18@email.com'),
       ('seojihwan', 'email19@email.com'),
       ('0imbean0', 'email20@email.com'),
       ('sunyoungkwon', 'email21@email.com'),
       ('hchayan', 'email22@email.com'),
       ('2sooy', 'email23@email.com'),
       ('yujo11', 'email24@email.com'),
       ('sunhpark42', 'email25@email.com')
;
