CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID  INT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    PRICE INT NOT NULL,
    IMAGE TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS MEMBER
(
    ID  INT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL
    );
