CREATE TABLE IF NOT EXISTS PRODUCT
(
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name       VARCHAR(255)    NOT NULL,
    image      VARCHAR(2083)   NOT NULL,
    price      INT UNSIGNED    NOT NULL,
    created_at DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS USERS
(
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name         VARCHAR(255),
    email        VARCHAR(255)    NOT NULL UNIQUE,
    password     VARCHAR(255)    NOT NULL,
    phone_number VARCHAR(20) UNIQUE,
    created_at   DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CART
(
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    users_id   BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    quantity   INT UNSIGNED    NOT NULL DEFAULT 1,
    created_at DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
