TRUNCATE TABLE orders_detail;
TRUNCATE TABLE orders;
TRUNCATE TABLE cart_item;
TRUNCATE TABLE product;
TRUNCATE TABLE customer;

ALTER TABLE orders_detail ALTER COLUMN id RESTART WITH 1;
ALTER TABLE orders ALTER COLUMN id RESTART WITH 1;
ALTER TABLE cart_item ALTER COLUMN id RESTART WITH 1;
ALTER TABLE customer ALTER COLUMN id RESTART WITH 1;
ALTER TABLE product ALTER COLUMN id RESTART WITH 1;
