CREATE TABLE IF NOT EXISTS PRODUCT
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(30)  NOT NULL,
    image_url VARCHAR(max) NOT NULL,
    price     INT          NOT NUll
    );

CREATE TABLE IF NOT EXISTS MEMBER
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS CART
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_id  BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);
