ALTER TABLE member
    ALTER COLUMN member_id RESTART WITH 1;
TRUNCATE TABLE member;

ALTER TABLE cart
    ALTER COLUMN cart_id RESTART WITH 1;
TRUNCATE TABLE cart;

ALTER TABLE product
    ALTER COLUMN product_id RESTART WITH 1;
TRUNCATE TABLE product;
