SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE PRODUCT;
TRUNCATE TABLE MEMBER;
TRUNCATE TABLE CART;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO member (email,password) VALUES('mango@wooteco.com','mangopassword');
