ALTER TABLE cart DROP CONSTRAINT member_fk;
ALTER TABLE cart DROP CONSTRAINT item_fk;
TRUNCATE TABLE cart RESTART IDENTITY;
TRUNCATE TABLE member RESTART IDENTITY;
TRUNCATE TABLE item RESTART IDENTITY;
ALTER TABLE cart ADD CONSTRAINT member_fk FOREIGN KEY (member_id) REFERENCES member (id);
ALTER TABLE cart ADD CONSTRAINT item_fk FOREIGN KEY (item_id) REFERENCES item (id);
